name: Task

on:
  workflow_dispatch:
    inputs:
    
      Team:
        type: choice
        description: Choose a Team
        options:
        - Byjus-Dev
        - Byjus-Prod
        - Byjus-Stagging
    
      Task:
        type: choice
        description: Choose a Task
        options:
        - GET
        - UPDATE
        - CREATE
        
      Secret_Name:
      
      Key1:
      Value1:
      
      Key2:
      Value2:
      
      Key3:
      Value3:
       
      Description:
      
jobs:

  Task:
    if: ${{ wf_triggered_user.Team == "Byjus-Dev" }}
    runs-on: [ ubuntu-latest]
    permissions:
        id-token: write
        contents: write
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ap-southeast-1
          role-skip-session-tagging: true

      - name: CREATE
        if: ${{ github.event.inputs.Task == 'CREATE' }}
        run:
          aws secretsmanager create-secret --name ${{ github.event.inputs.Secret_Name}} --secret-string '{"${{ github.event.inputs.Key1}}":"${{ github.event.inputs.Value1}}", "${{ github.event.inputs.Key2}}":"${{ github.event.inputs.Value2}}", "${{ github.event.inputs.Key3}}":"${{ github.event.inputs.Value3}}"}' 
      
      - name: GET    
        if: ${{ github.event.inputs.Task == 'GET' }}
        run: aws secretsmanager get-secret-value --secret-id ${{ github.event.inputs.Secret_Name}}
        
      - name: UPDATE   
        id: update
        if: ${{ github.event.inputs.Task == 'UPDATE' }}
        run:
          aws secretsmanager get-secret-value --secret-id ${{ github.event.inputs.Secret_Name}}
      
      - name: UPDATE_NOW   
        if: steps.update.outcome=='success'
        run:
          aws secretsmanager update-secret --secret-id ${{github.event.inputs.Secret_Name}} --secret-string '{"${{ github.event.inputs.Key1}}":"${{ github.event.inputs.Value1}}", "${{ github.event.inputs.Key2}}":"${{ github.event.inputs.Value2}}", "${{ github.event.inputs.Key3}}":"${{ github.event.inputs.Value3}}"}'
